[mongodb]
mongodb.kodari.online 
[catalogue]
catalogue.kodari.online
[redis]
redis.kodari.online
[frontend]
frontend.kodari.online
[user]
user.kodari.online
[cart]
cart.kodari.online
[shipping]
shipping.kodari.online
[mysql]
mysql.kodari.online
[rabbitmq]
rabbitmq.kodari.online
[payment]
payment.kodari.online 

; [all:vars]
; ansible_user=ec2-user
; ansible_password=DevOps321 

; [localhost]
; local



; [local]
; localhost

; [mongodb]
; localhost

; [redis]
; localhost

; [mysql]
; localhost

; [rabbitmq]
; localhost

; [catalogue]
; localhost

; [user]
; localhost

; [cart]
; localhost

; [shipping]
; localhost

; [payment]
; localhost

; [frontend]
; localhost