- name: app-setup
  include_role:
     name: common
     tasks_from: app-setup

- name: nodejs
  include_role:
     name: common
     tasks_from: nodejs

- name: systemd setup  
  include_role:
    name: common
    tasks_from: systemd.yaml


# include role go and check fetch the tasks from common role /appp.setup excute now means during excution 